name: saferide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  sensors_plus: ^6.1.1
  geolocator: ^14.0.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  provider: ^6.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
